#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EveryRecords.Resource", IsApplication=true)]

namespace EveryRecords
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050012
			public const int AddButton = 2131034130;
			
			// aapt resource value: 0x7f050006
			public const int AmountText = 2131034118;
			
			// aapt resource value: 0x7f05000a
			public const int BackButton = 2131034122;
			
			// aapt resource value: 0x7f05000f
			public const int CategoryItems = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int CommentsText = 2131034120;
			
			// aapt resource value: 0x7f050013
			public const int DeleteButton = 2131034131;
			
			// aapt resource value: 0x7f050003
			public const int ExitButton = 2131034115;
			
			// aapt resource value: 0x7f050010
			public const int NodeText = 2131034128;
			
			// aapt resource value: 0x7f050004
			public const int PathString = 2131034116;
			
			// aapt resource value: 0x7f05000b
			public const int PathText = 2131034123;
			
			// aapt resource value: 0x7f050000
			public const int RecordButton = 2131034112;
			
			// aapt resource value: 0x7f05000c
			public const int ReportsList = 2131034124;
			
			// aapt resource value: 0x7f050009
			public const int SaveButton = 2131034121;
			
			// aapt resource value: 0x7f050002
			public const int SettingButton = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int UpLevelButton = 2131034126;
			
			// aapt resource value: 0x7f050001
			public const int ViewReportButton = 2131034113;
			
			// aapt resource value: 0x7f050011
			public const int linearLayout1 = 2131034129;
			
			// aapt resource value: 0x7f05000d
			public const int linearLayout2 = 2131034125;
			
			// aapt resource value: 0x7f050005
			public const int textView3 = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int textView4 = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int RecordingLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ReportingLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int SettingLayout = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040008
			public const int Add = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int Amount = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04000a
			public const int Back = 2130968586;
			
			// aapt resource value: 0x7f040006
			public const int Comments = 2130968582;
			
			// aapt resource value: 0x7f040009
			public const int Delete = 2130968585;
			
			// aapt resource value: 0x7f04000c
			public const int Exit = 2130968588;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Record = 2130968578;
			
			// aapt resource value: 0x7f040007
			public const int Save = 2130968583;
			
			// aapt resource value: 0x7f040004
			public const int Setting = 2130968580;
			
			// aapt resource value: 0x7f04000b
			public const int UpLevel = 2130968587;
			
			// aapt resource value: 0x7f040003
			public const int ViewReport = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
