#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EveryRecords.Resource", IsApplication=true)]

namespace EveryRecords
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int PushLeftIn = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int PushLeftOut = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int PushRightIn = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int PushRightOut = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int a = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int b = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int c = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int d = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int e = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int EveryRecords = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int EveryRecords_small = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int FunctionButton = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int PercentageBackground = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int TitleButton = 2130837514;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f08003b
			public const int AddAmountButton = 2131230779;
			
			// aapt resource value: 0x7f08000d
			public const int AddButton = 2131230733;
			
			// aapt resource value: 0x7f080043
			public const int AllowDeleteHistoryCheck = 2131230787;
			
			// aapt resource value: 0x7f080042
			public const int AllowDeleteRecordCheck = 2131230786;
			
			// aapt resource value: 0x7f080039
			public const int AmountLabel = 2131230777;
			
			// aapt resource value: 0x7f08003a
			public const int AmountTextBox = 2131230778;
			
			// aapt resource value: 0x7f080003
			public const int BackButton = 2131230723;
			
			// aapt resource value: 0x7f080028
			public const int BottomLayout = 2131230760;
			
			// aapt resource value: 0x7f080012
			public const int CancelButton = 2131230738;
			
			// aapt resource value: 0x7f080027
			public const int CategoryButton = 2131230759;
			
			// aapt resource value: 0x7f08000e
			public const int CategoryItems = 2131230734;
			
			// aapt resource value: 0x7f080036
			public const int CategoryList = 2131230774;
			
			// aapt resource value: 0x7f080020
			public const int Col1Layout = 2131230752;
			
			// aapt resource value: 0x7f080022
			public const int Col2Layout = 2131230754;
			
			// aapt resource value: 0x7f080024
			public const int Col3Layout = 2131230756;
			
			// aapt resource value: 0x7f080026
			public const int Col4Layout = 2131230758;
			
			// aapt resource value: 0x7f08003d
			public const int CommentsText = 2131230781;
			
			// aapt resource value: 0x7f080007
			public const int ContentLayout = 2131230727;
			
			// aapt resource value: 0x7f080010
			public const int ContentText = 2131230736;
			
			// aapt resource value: 0x7f08001a
			public const int ExitButton = 2131230746;
			
			// aapt resource value: 0x7f080041
			public const int ExpensesLimitText = 2131230785;
			
			// aapt resource value: 0x7f080025
			public const int HistoryButton = 2131230757;
			
			// aapt resource value: 0x7f080013
			public const int HistoryList = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int ImagesView = 2131230740;
			
			// aapt resource value: 0x7f080009
			public const int IntroduceButton = 2131230729;
			
			// aapt resource value: 0x7f08001f
			public const int MiddleLayout = 2131230751;
			
			// aapt resource value: 0x7f08001d
			public const int MiddleTopLayout = 2131230749;
			
			// aapt resource value: 0x7f08000c
			public const int NodeText = 2131230732;
			
			// aapt resource value: 0x7f080011
			public const int OkButton = 2131230737;
			
			// aapt resource value: 0x7f080035
			public const int PathString = 2131230773;
			
			// aapt resource value: 0x7f08001e
			public const int PercentLayout = 2131230750;
			
			// aapt resource value: 0x7f08002a
			public const int Recent1 = 2131230762;
			
			// aapt resource value: 0x7f080029
			public const int Recent1Layout = 2131230761;
			
			// aapt resource value: 0x7f08002c
			public const int Recent2 = 2131230764;
			
			// aapt resource value: 0x7f08002b
			public const int Recent2Layout = 2131230763;
			
			// aapt resource value: 0x7f08002e
			public const int Recent3 = 2131230766;
			
			// aapt resource value: 0x7f08002d
			public const int Recent3Layout = 2131230765;
			
			// aapt resource value: 0x7f080030
			public const int Recent4 = 2131230768;
			
			// aapt resource value: 0x7f08002f
			public const int Recent4Layout = 2131230767;
			
			// aapt resource value: 0x7f080032
			public const int Recent5 = 2131230770;
			
			// aapt resource value: 0x7f080031
			public const int Recent5Layout = 2131230769;
			
			// aapt resource value: 0x7f080034
			public const int Recent6 = 2131230772;
			
			// aapt resource value: 0x7f080033
			public const int Recent6Layout = 2131230771;
			
			// aapt resource value: 0x7f080021
			public const int RecordButton = 2131230753;
			
			// aapt resource value: 0x7f080044
			public const int RecordList = 2131230788;
			
			// aapt resource value: 0x7f08003f
			public const int ReportsList = 2131230783;
			
			// aapt resource value: 0x7f080016
			public const int RootLayout = 2131230742;
			
			// aapt resource value: 0x7f08003e
			public const int SaveButton = 2131230782;
			
			// aapt resource value: 0x7f080040
			public const int SelectionList = 2131230784;
			
			// aapt resource value: 0x7f080019
			public const int SettingButton = 2131230745;
			
			// aapt resource value: 0x7f080045
			public const int Settings = 2131230789;
			
			// aapt resource value: 0x7f080006
			public const int SubTitleText = 2131230726;
			
			// aapt resource value: 0x7f08001c
			public const int SummaryText = 2131230748;
			
			// aapt resource value: 0x7f080001
			public const int TitleInnerLayout = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int TitleLayout = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int TitleStringLayout = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int TitleSubLayout = 2131230725;
			
			// aapt resource value: 0x7f08000f
			public const int TitleText = 2131230735;
			
			// aapt resource value: 0x7f080018
			public const int VerButton = 2131230744;
			
			// aapt resource value: 0x7f080023
			public const int ViewReportButton = 2131230755;
			
			// aapt resource value: 0x7f080015
			public const int linearLayout1 = 2131230741;
			
			// aapt resource value: 0x7f08001b
			public const int linearLayout10 = 2131230747;
			
			// aapt resource value: 0x7f08000a
			public const int linearLayout2 = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int linearLayout3 = 2131230731;
			
			// aapt resource value: 0x7f080038
			public const int linearLayout4 = 2131230776;
			
			// aapt resource value: 0x7f080017
			public const int linearLayout9 = 2131230743;
			
			// aapt resource value: 0x7f080008
			public const int textView1 = 2131230728;
			
			// aapt resource value: 0x7f080037
			public const int textView3 = 2131230775;
			
			// aapt resource value: 0x7f08003c
			public const int textView4 = 2131230780;
			
			// aapt resource value: 0x7f080004
			public const int titleText = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CategoryLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ConfirmLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HistoryLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int IntroductionLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ListviewItemLayout = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int RecordingLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int ReportingLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SelectionLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int SettingLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int StartRecordingLayout = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int AppMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050014
			public const int About = 2131034132;
			
			// aapt resource value: 0x7f050019
			public const int AboutApp = 2131034137;
			
			// aapt resource value: 0x7f050009
			public const int Add = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int AddCategory = 2131034129;
			
			// aapt resource value: 0x7f050018
			public const int AllowDeleteHistory = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int AllowDeleteRecord = 2131034135;
			
			// aapt resource value: 0x7f050006
			public const int Amount = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int Back = 2131034123;
			
			// aapt resource value: 0x7f050016
			public const int Cancel = 2131034134;
			
			// aapt resource value: 0x7f050013
			public const int Category = 2131034131;
			
			// aapt resource value: 0x7f050007
			public const int Comments = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int Delete = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int EditCategory = 2131034130;
			
			// aapt resource value: 0x7f05000d
			public const int Exit = 2131034125;
			
			// aapt resource value: 0x7f05001b
			public const int ExpensesLimit = 2131034139;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int HistoryRec = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int HistoryTitle = 2131034128;
			
			// aapt resource value: 0x7f05001a
			public const int Introduce = 2131034138;
			
			// aapt resource value: 0x7f050015
			public const int Ok = 2131034133;
			
			// aapt resource value: 0x7f050002
			public const int Record = 2131034114;
			
			// aapt resource value: 0x7f05000e
			public const int RecordTitle = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int ReportTitle = 2131034127;
			
			// aapt resource value: 0x7f050008
			public const int Save = 2131034120;
			
			// aapt resource value: 0x7f050005
			public const int Setting = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int UpLevel = 2131034124;
			
			// aapt resource value: 0x7f050003
			public const int ViewReport = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int PopupTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
