#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("EveryRecords.Resource", IsApplication=true)]

namespace EveryRecords
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int EveryRecords = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int EveryRecords_small = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int MetroButton = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050026
			public const int AddAmountButton = 2131034150;
			
			// aapt resource value: 0x7f05000a
			public const int AddButton = 2131034122;
			
			// aapt resource value: 0x7f05002d
			public const int AddText = 2131034157;
			
			// aapt resource value: 0x7f050024
			public const int AmountLabel = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int AmountTextBox = 2131034149;
			
			// aapt resource value: 0x7f050002
			public const int BackButton = 2131034114;
			
			// aapt resource value: 0x7f05000f
			public const int CancelButton = 2131034127;
			
			// aapt resource value: 0x7f050020
			public const int CategoryButton = 2131034144;
			
			// aapt resource value: 0x7f05000b
			public const int CategoryItems = 2131034123;
			
			// aapt resource value: 0x7f050022
			public const int CategoryList = 2131034146;
			
			// aapt resource value: 0x7f050028
			public const int CommentsText = 2131034152;
			
			// aapt resource value: 0x7f05000d
			public const int ContentText = 2131034125;
			
			// aapt resource value: 0x7f050015
			public const int ExitButton = 2131034133;
			
			// aapt resource value: 0x7f05001e
			public const int HistoryButton = 2131034142;
			
			// aapt resource value: 0x7f050010
			public const int HistoryList = 2131034128;
			
			// aapt resource value: 0x7f050009
			public const int NodeText = 2131034121;
			
			// aapt resource value: 0x7f05000e
			public const int OkButton = 2131034126;
			
			// aapt resource value: 0x7f050021
			public const int PathString = 2131034145;
			
			// aapt resource value: 0x7f05001a
			public const int RecordButton = 2131034138;
			
			// aapt resource value: 0x7f05002c
			public const int RecordList = 2131034156;
			
			// aapt resource value: 0x7f05002a
			public const int ReportsList = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int SaveText = 2131034153;
			
			// aapt resource value: 0x7f05002b
			public const int SelectionList = 2131034155;
			
			// aapt resource value: 0x7f050014
			public const int SettingButton = 2131034132;
			
			// aapt resource value: 0x7f050005
			public const int SubTitleText = 2131034117;
			
			// aapt resource value: 0x7f050017
			public const int SummaryText = 2131034135;
			
			// aapt resource value: 0x7f050001
			public const int TitleInnerLayout = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int TitleLayout = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int TitleSubLayout = 2131034116;
			
			// aapt resource value: 0x7f050011
			public const int TitleText = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int VerButton = 2131034131;
			
			// aapt resource value: 0x7f05001c
			public const int ViewReportButton = 2131034140;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayout1 = 2131034124;
			
			// aapt resource value: 0x7f050016
			public const int linearLayout10 = 2131034134;
			
			// aapt resource value: 0x7f050006
			public const int linearLayout2 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int linearLayout3 = 2131034120;
			
			// aapt resource value: 0x7f050018
			public const int linearLayout4 = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int linearLayout5 = 2131034137;
			
			// aapt resource value: 0x7f05001b
			public const int linearLayout6 = 2131034139;
			
			// aapt resource value: 0x7f05001d
			public const int linearLayout7 = 2131034141;
			
			// aapt resource value: 0x7f05001f
			public const int linearLayout8 = 2131034143;
			
			// aapt resource value: 0x7f050012
			public const int linearLayout9 = 2131034130;
			
			// aapt resource value: 0x7f050007
			public const int textView1 = 2131034119;
			
			// aapt resource value: 0x7f050023
			public const int textView3 = 2131034147;
			
			// aapt resource value: 0x7f050027
			public const int textView4 = 2131034151;
			
			// aapt resource value: 0x7f050003
			public const int titleText = 2131034115;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AboutLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CategoryLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ConfirmLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int HistoryLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ListviewItemLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int RecordingLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ReportingLayout = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int SelectionLayout = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int SettingLayout = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int StartRecordingLayout = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040014
			public const int About = 2130968596;
			
			// aapt resource value: 0x7f040009
			public const int Add = 2130968585;
			
			// aapt resource value: 0x7f040011
			public const int AddCategory = 2130968593;
			
			// aapt resource value: 0x7f040006
			public const int Amount = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f04000b
			public const int Back = 2130968587;
			
			// aapt resource value: 0x7f040016
			public const int Cancel = 2130968598;
			
			// aapt resource value: 0x7f040013
			public const int Category = 2130968595;
			
			// aapt resource value: 0x7f040007
			public const int Comments = 2130968583;
			
			// aapt resource value: 0x7f04000a
			public const int Delete = 2130968586;
			
			// aapt resource value: 0x7f040012
			public const int EditCategory = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int Exit = 2130968589;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int HistoryRec = 2130968580;
			
			// aapt resource value: 0x7f040010
			public const int HistoryTitle = 2130968592;
			
			// aapt resource value: 0x7f040015
			public const int Ok = 2130968597;
			
			// aapt resource value: 0x7f040002
			public const int Record = 2130968578;
			
			// aapt resource value: 0x7f04000e
			public const int RecordTitle = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int ReportTitle = 2130968591;
			
			// aapt resource value: 0x7f040008
			public const int Save = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int Setting = 2130968581;
			
			// aapt resource value: 0x7f04000c
			public const int UpLevel = 2130968588;
			
			// aapt resource value: 0x7f040003
			public const int ViewReport = 2130968579;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
